# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 05:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('genres', models.ManyToManyField(to='genres.Genre')),
            ],
            options={
                'verbose_name_plural': 'Tracks',
            },
        ),
    ]
